name: Docker Image CI

on:
#  workflow_dispatch
  push:
    branches: [ "feature/regex" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        cd Cat && docker build . -t lindalu/cat:action10
        cd ../helloworld && docker build . -t lindalu/helloworld:action10
        cd ../web-nginx && docker build . -t lindalu/mynginx:action10
        
    - name: Upload the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push lindalu/cat:action10
        docker push lindalu/helloworld:action10
        docker push lindalu/mynginx:action10

    - name: SSH to Remote Server and Run docker-compose
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 20.5.201.59
        username: linda
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22        
        script: |
          echo "Running command on remote server"
          cd ~/Linda_Docker-1
          git pull
          docker-compose down
          docker-compose up -d
          docker-compose ps        
